"""One-off patch: enrich LLMImageDescription for remaining stormy story scenes."""
import json
from pathlib import Path

STORY = Path("game/data/stories/stormy-the-archer-intro.json")

ART = (
    "A needle-felted wool diorama photographed like a handmade craft scene. "
    "Characters are chibi-style - small, round, simple bodies with oversized heads, "
    "cute and hand-shaped, slightly lumpy and imperfect, with visible needle-felting "
    "texture and wispy loose wool fibers around the edges. All features are made of "
    "felt: eyes are simple small felted dots or flat felt shapes (no glass, no shine, "
    "no reflections, no highlights), and mouths and other details are also simple "
    "felted shapes. Environments are simple with just a few felted objects. Earthy, "
    "muted color palette, warm moody lighting with soft shadows, shallow depth of "
    "field so the scene feels like a real physical diorama."
)

UPDATES = {
    "the_pitch": (
        f"{ART} A small open square in town with simple felted buildings around the "
        "edges and a packed-dirt floor. Reference images are provided in this order: "
        "first Stormy, second the jerboa, third the rat, and fourth the tonic cart. "
        "the rat, matching the third reference image — A brown giant rat tonic-salesman "
        "wearing a patched black top hat, a tailored dark coat over a smart buttoned "
        "vest with a brass watch chain, and a small bow tie, with a long pink tail. — "
        "stands beside the cart in the center foreground with one paw lifted high in a "
        "sharp shooing gesture, his other paw still holding his top hat at his side. "
        "His grin has dropped completely — his eyes are narrowed in annoyance and his "
        "mouth is pulled into a flat irritated line. the tonic cart, matching the "
        "fourth reference image — A small wooden sales cart on two wheels with a muted "
        "red canopy roof and a muted teal body, the painted surfaces lightly worn but a "
        "single solid color each, with the wheels, pull-handle, and structural posts "
        "left as natural warm wood. The shelves hold assorted tonic wares — small glass "
        "bottles, little stoppered vials, ceramic jars, paper-wrapped packets, and "
        "small bundles of dried herbs. No text or labels anywhere on the cart. — sits "
        "directly behind him, stacked with little bottles. Stormy, matching the first "
        "reference image — A grey rabbit archer wearing a green cloak, with a small "
        "quiver of felted arrows on his back, carrying a wooden bow. — stands near the "
        "cart on the left side of the frame with his weight planted and both paws at "
        "his sides, refusing to leave. His ears are stiff and angled forward, his eyes "
        "are narrowed with wary stubborn focus, and his mouth is set in a tight "
        "unmoving frown. the jerboa, matching the second reference image — A sandy-tan "
        "desert jerboa with huge ears and long back legs, wearing a chunky cream "
        "knitted sweater and matching leg warmers. — hops away in the background "
        "clutching her tiny tonic bottle to her chest, one long leg mid-stride, her "
        "mouth curled in a satisfied little smile. the rat shooes Stormy; the jerboa "
        "leaves in the background. Do not swap their roles. Warm town-square light. "
        "Stormy matches the first reference; the jerboa matches the second reference; "
        "the rat matches the third reference; the tonic cart matches the fourth reference."
    ),
    "rat_shoos_stormy": (
        f"{ART} A small open square in town with simple felted buildings around the "
        "edges and a packed-dirt floor. Reference images are provided in this order: "
        "first Stormy, second the rat, and third the tonic cart. the tonic cart, "
        "matching the third reference image — A small wooden sales cart on two wheels "
        "with a muted red canopy roof and a muted teal body, the painted surfaces "
        "lightly worn but a single solid color each, with the wheels, pull-handle, and "
        "structural posts left as natural warm wood. The shelves hold assorted tonic "
        "wares — small glass bottles, little stoppered vials, ceramic jars, "
        "paper-wrapped packets, and small bundles of dried herbs. No text or labels "
        "anywhere on the cart. — sits between and behind the two characters in the "
        "center background. Stormy, matching the first reference image — A grey rabbit "
        "archer wearing a green cloak, with a small quiver of felted arrows on his "
        "back, carrying a wooden bow. — faces the rat in the left foreground with both "
        "arms folded tight across his chest, feet planted wide, ears stiff and angled "
        "forward. His eyes are narrowed with stubborn focus and his mouth is pressed "
        "into a hard unyielding line. the rat, matching the second reference image — A "
        "brown giant rat tonic-salesman wearing a patched black top hat, a tailored "
        "dark coat over a smart buttoned vest with a brass watch chain, and a small "
        "bow tie, with a long pink tail. — stands opposite him on the right with his "
        "own arms folded bigger across his chest, chin lifted, eyes half-lidded in "
        "irritated disbelief, and his mouth twisted into a sour frown. Stormy and the "
        "rat face off beside the cart with arms folded; neither runs the course. Do "
        "not swap their roles. Warm town-square light. Stormy matches the first "
        "reference; the rat matches the second reference; the tonic cart matches the "
        "third reference."
    ),
    "pellet_insult": (
        f"{ART} A small open square in town with simple felted buildings around the "
        "edges and a packed-dirt floor. Reference images are provided in this order: "
        "first Stormy, second the rat, and third the tonic cart. the tonic cart, "
        "matching the third reference image — A small wooden sales cart on two wheels "
        "with a muted red canopy roof and a muted teal body, the painted surfaces "
        "lightly worn but a single solid color each, with the wheels, pull-handle, and "
        "structural posts left as natural warm wood. The shelves hold assorted tonic "
        "wares — small glass bottles, little stoppered vials, ceramic jars, "
        "paper-wrapped packets, and small bundles of dried herbs. No text or labels "
        "anywhere on the cart. — with little bottles stacked behind him sits beside the "
        "rat in the background. the rat, matching the second reference image — A brown "
        "giant rat tonic-salesman wearing a patched black top hat, a tailored dark "
        "coat over a smart buttoned vest with a brass watch chain, and a small bow "
        "tie, with a long pink tail. — leans forward from the right side of the frame "
        "and holds out a dusty little felted bag of rabbit pellets in one extended paw, "
        "his other paw on his hip. His eyes are half-lidded with smug amusement and "
        "his mouth is curled into a condescending grin. Stormy, matching the first "
        "reference image — A grey rabbit archer wearing a green cloak, with a small "
        "quiver of felted arrows on his back, carrying a wooden bow. — stands facing "
        "him in the left foreground with both paws clenched at his sides, ears bolt "
        "upright and stiff with offense, cheeks flushed bright pink-red, eyes narrowed "
        "into furious slits, and his mouth pulled into a deeply offended scowl. The "
        "cart and pellets should be easy to read, but Stormy's insulted reaction is "
        "the focus. Warm town-square light. Stormy matches the first reference; the "
        "rat matches the second reference; the tonic cart matches the third reference."
    ),
    "rat_directions_fail": (
        f"{ART} A vast sandy desert with rolling dunes under a hot sun. A dusty road "
        "cuts through the sand, with the last small town buildings far behind and open "
        "sand ahead. Use the reference image for Stormy. Stormy, matching the first "
        "reference image — A grey rabbit archer wearing a green cloak, with a small "
        "quiver of felted arrows on his back, carrying a wooden bow. — sprints full "
        "speed down the road in the foreground, body leaned forward, one paw reaching "
        "far ahead and the other pushing off the dirt behind him. His long ears stream "
        "flat backward, his bow bounces on his back, and his cloak flutters behind "
        "him. His eyes are wide and fixed ahead searching desperately for a windmill, "
        "and his mouth is open in a breathless determined grimace. No windmill is "
        "visible anywhere. Hot sunlit desert light. Stormy matches the reference."
    ),
    "no_windmill": (
        f"{ART} A vast sandy desert with rolling dunes under a hot sun. Use the "
        "reference image for Stormy. Stormy, matching the first reference image — A "
        "grey rabbit archer wearing a green cloak, with a small quiver of felted "
        "arrows on his back, carrying a wooden bow. — stands stopped in the sand in "
        "the foreground with slumped shoulders, one paw hanging limp at his side and "
        "the other resting on his hip, his bow dragging slightly. His ears droop "
        "forward, his eyes look hollow and defeated as he realizes he has been "
        "tricked, and his mouth is pulled into a small miserable frown. Beside him "
        "stands a simple chibi felted camel looking at him skeptically with flat "
        "unimpressed eyes and a neutral mouth. No rat and no windmill are visible "
        "anywhere. Hot sunlit desert light. Stormy matches the reference."
    ),
    "graveyard_search": (
        f"{ART} A small graveyard with a few weathered gravestones, a bare spooky "
        "tree with no leaves, and a full moon hanging in the sky. Use the reference "
        "image for Stormy. Stormy, matching the first reference image — A grey rabbit "
        "archer wearing a green cloak, with a small quiver of felted arrows on his "
        "back, carrying a wooden bow. — stands among crooked old headstones in the "
        "foreground, leaning forward to read one stone with one paw braced against "
        "its edge and the other paw pointing at a carved marking. His ears are tilted "
        "forward with concentration, his eyes are narrowed and a little worried, and "
        "his mouth is held in a small tense thoughtful line. Cool moonlit graveyard "
        "light, mildly spooky but still handmade and child-friendly. Stormy matches "
        "the reference."
    ),
    "catacombs_descent": (
        f"{ART} A side view of a set of stone stairs leading down underground into "
        "darkness. Grass and a shifted headstone sit above the opening. Use the "
        "reference image for Stormy. Stormy, matching the first reference image — A "
        "grey rabbit archer wearing a green cloak, with a small quiver of felted "
        "arrows on his back, carrying a wooden bow. — crouches on one knee beside the "
        "open entrance in the foreground, leaning forward with one paw gripping the "
        "edge of the shifted headstone and the other paw braced on the grass. He "
        "peers down into the darkness below. His ears are angled forward and slightly "
        "lowered with caution, his eyes look determined but wary, and his mouth is set "
        "in a small tight line. Dim cool light at the stair opening leading into "
        "shadow. Stormy matches the reference."
    ),
    "the_dangling_key": (
        f"{ART} An underground stone chamber with broken pillars fallen across the "
        "floor, narrow ledges along the walls, and dark gaps in the stone. A skeleton "
        "key hangs on a string from the ceiling at the center. Reference images are "
        "provided in this order: first Stormy, second the skeleton key. the skeleton "
        "key, matching the second reference image — A small iron skeleton key with a "
        "wooden tag-like handle. A symbol is carved into the handle: sharp lines, a "
        "round moon, and a shape like a little door. — hangs from a thin string in "
        "the center of the chamber high above the floor, turning slowly with a slight "
        "tilt. Stormy, matching the first reference image — A grey rabbit archer "
        "wearing a green cloak, with a small quiver of felted arrows on his back, "
        "carrying a wooden bow. — stands below in the foreground with his bow drawn "
        "to his cheek, one felted arrow nocked and aimed carefully upward at the "
        "string. His front paw pulls the string back, his back paw is planted wide "
        "for balance, his ears are pinned back in focus, his eyes are narrowed to "
        "slits along the arrow, and his mouth is pressed into a determined line. Dim "
        "underground light with soft shadows. Stormy matches the first reference; the "
        "skeleton key matches the second reference."
    ),
    "key_lost": (
        f"{ART} An underground stone chamber with broken pillars fallen across the "
        "floor, narrow ledges along the walls, and dark gaps in the stone. Reference "
        "images are provided in this order: first Stormy, second the skeleton key. "
        "Stormy, matching the first reference image — A grey rabbit archer wearing a "
        "green cloak, with a small quiver of felted arrows on his back, carrying a "
        "wooden bow. — stands in the foreground with his bow lowered suddenly in both "
        "paws, shoulders hunched. His ears stick straight up in alarm, his eyes are "
        "wide round dots of shock, and his mouth is open in a small horrified O of "
        "realization. the skeleton key, matching the second reference image — A "
        "small iron skeleton key with a wooden tag-like handle. A symbol is carved "
        "into the handle: sharp lines, a round moon, and a shape like a little door. "
        "— is visible mid-flight near a dark gap in the stone, knocked sideways by "
        "Stormy's arrow which trails just behind it. Dim underground light with soft "
        "shadows. The skeleton key is mid-flight into darkness — Stormy otherwise "
        "matches the first reference."
    ),
    "key_in_paw": (
        f"{ART} A close-up view of Stormy striking a triumphant pose, with stone "
        "walls dimly visible in the background. Reference images are provided in this "
        "order: first Stormy, second the skeleton key. Stormy, matching the first "
        "reference image — A grey rabbit archer wearing a green cloak, with a small "
        "quiver of felted arrows on his back, carrying a wooden bow. — stands in the "
        "center with one paw held out palm-up to catch the falling key and his other "
        "paw gripping his bow at his side. His ears are perked tall, his eyes are "
        "bright with relief and quiet pride, and his mouth is curled into a small "
        "satisfied smile. the skeleton key, matching the second reference image — A "
        "small iron skeleton key with a wooden tag-like handle. A symbol is carved "
        "into the handle: sharp lines, a round moon, and a shape like a little door. "
        "— drops neatly into his waiting paw from above. A few small bits of snapped "
        "string drift nearby. Warm dim underground light with soft shadows. Stormy "
        "matches the first reference; the skeleton key matches the second reference."
    ),
    "studying_the_key": (
        f"{ART} A small open square in town with simple felted buildings around the "
        "edges and a packed-dirt floor. The tonic cart sits soft in the background. "
        "Reference images are provided in this order: first Stormy, second the "
        "skeleton key. Stormy, matching the first reference image — A grey rabbit "
        "archer wearing a green cloak, with a small quiver of felted arrows on his "
        "back, carrying a wooden bow. — sits on a low stone step in the foreground "
        "holding the skeleton key close in both paws, turning it over to study the "
        "symbol carved into its handle. His ears are tilted forward, his eyes are "
        "narrowed in puzzlement, and his mouth is pulled into a small thoughtful "
        "frown with one corner slightly downturned. the skeleton key, matching the "
        "second reference image — A small iron skeleton key with a wooden tag-like "
        "handle. A symbol is carved into the handle: sharp lines, a round moon, and a "
        "shape like a little door. — is held large in the composition so the carved "
        "symbol is easy to read. Warm quiet town-square light. Stormy matches the "
        "first reference; the skeleton key matches the second reference."
    ),
    "rat_returns": (
        f"{ART} A small open square in town with simple felted buildings around the "
        "edges and a packed-dirt floor. The tonic cart is visible nearby. Reference "
        "images are provided in this order: first Stormy, second the rat, and third "
        "the skeleton key. Stormy, matching the first reference image — A grey rabbit "
        "archer wearing a green cloak, with a small quiver of felted arrows on his "
        "back, carrying a wooden bow. — holds the skeleton key in both paws at chest "
        "height and turns his head over one shoulder with guarded surprise, one ear "
        "twisted back toward the rat. His eyes are wide and wary, and his mouth is "
        "held in a tight uncertain line. the rat, matching the second reference image "
        "— A brown giant rat tonic-salesman wearing a patched black top hat, a "
        "tailored dark coat over a smart buttoned vest with a brass watch chain, and a "
        "small bow tie, with a long pink tail. — leans over Stormy's shoulder from "
        "behind, his face close to the key, his grin completely gone. His eyes are "
        "fixed wide on the metal, his ears are forward, and his mouth is slightly "
        "parted in stunned surprise. Keep the composition close, with the key between "
        "them as the clear focus. Warm town-square light. Stormy matches the first "
        "reference; the rat matches the second reference; the skeleton key matches "
        "the third reference."
    ),
    "yell_branch": (
        f"{ART} A small open square in town with simple felted buildings around the "
        "edges and a packed-dirt floor. The tonic cart sits beside them. Reference "
        "images are provided in this order: first Stormy, second the rat, and third "
        "the skeleton key. Stormy, matching the first reference image — A grey rabbit "
        "archer wearing a green cloak, with a small quiver of felted arrows on his "
        "back, carrying a wooden bow. — faces the rat in the left foreground with "
        "one paw thrust forward pointing at him and the other paw clutching the "
        "skeleton key protectively against his chest. His ears are bolt upright and "
        "stiff with anger, his cheeks are flushed bright pink-red, his eyes are "
        "narrowed into furious slits, and his mouth is open wide shouting. the rat, "
        "matching the second reference image — A brown giant rat tonic-salesman wearing "
        "a patched black top hat, a tailored dark coat over a smart buttoned vest with "
        "a brass watch chain, and a small bow tie, with a long pink tail. — steps "
        "backward on the right with both paws raised high in exaggerated offended "
        "surrender, his eyes wide with mock hurt, and his mouth pulled into a wounded "
        "pout. Warm town-square light. Stormy matches the first reference; the rat "
        "matches the second reference; the skeleton key matches the third reference."
    ),
    "woods_fail": (
        f"{ART} A dense forest filled with thick tangled brambles. Reference images "
        "are provided in this order: first Stormy, second the skeleton key. Stormy, "
        "matching the first reference image — A grey rabbit archer wearing a green "
        "cloak, with a small quiver of felted arrows on his back, carrying a wooden "
        "bow. — stands caught in the brambles in the foreground with his cloak tugged "
        "and twisted in three different directions by thorny vines, one paw trying "
        "to pull a bramble off his shoulder and the other still clutching the "
        "skeleton key. His ears are pinned back in frustration, his eyes are narrowed "
        "and annoyed, and his mouth is pulled into an exasperated frown. the skeleton "
        "key, matching the second reference image — A small iron skeleton key with a "
        "wooden tag-like handle. A symbol is carved into the handle: sharp lines, a "
        "round moon, and a shape like a little door. — remains visible in his paw. A "
        "simple felted squirrel sits on a branch nearby staring at him with flat "
        "unimpressed eyes. Warm moody forest light, funny and mildly frustrating, not "
        "scary. Stormy matches the first reference; the skeleton key matches the "
        "second reference."
    ),
    "sewer_fail": (
        f"{ART} A stone tunnel with a channel of gross looking water running down the "
        "middle. Reference images are provided in this order: first Stormy, second the "
        "skeleton key. Stormy, matching the first reference image — A grey rabbit "
        "archer wearing a green cloak, with a small quiver of felted arrows on his "
        "back, carrying a wooden bow. — stands in the damp tunnel in the foreground "
        "with one paw pinched over his nose and the other arm extended holding the "
        "skeleton key as far from the gross water as possible. His ears droop sideways "
        "in disgust, his eyes are squeezed nearly shut, and his mouth is scrunched "
        "into a tight stinky grimace. the skeleton key, matching the second reference "
        "image — A small iron skeleton key with a wooden tag-like handle. A symbol is "
        "carved into the handle: sharp lines, a round moon, and a shape like a little "
        "door. — dangles from his extended paw. Dim tunnel light, simple and gross but "
        "still handmade and child-friendly. Stormy matches the first reference; the "
        "skeleton key matches the second reference."
    ),
    "rat_reads_key": (
        f"{ART} A small open square in town with simple felted buildings around the "
        "edges and a packed-dirt floor. The bright tonic cart sits nearby. Reference "
        "images are provided in this order: first Stormy, second the rat, and third "
        "the skeleton key. the rat, matching the second reference image — A brown "
        "giant rat tonic-salesman wearing a patched black top hat, a tailored dark "
        "coat over a smart buttoned vest with a brass watch chain, and a small bow "
        "tie, with a long pink tail. — leans in close from the right side, squinting "
        "hard at the symbol on Stormy's skeleton key with one paw braced on Stormy's "
        "shoulder. His eyes are narrowed to slits, his nose is almost touching the "
        "key, and his mouth is pulled into a calculating thoughtful pout. Stormy, "
        "matching the first reference image — A grey rabbit archer wearing a green "
        "cloak, with a small quiver of felted arrows on his back, carrying a wooden "
        "bow. — holds the key out in both paws in the center of the frame, watching "
        "the rat carefully with guarded suspicious eyes, one ear angled toward the rat "
        "and the other forward. His free paw is tensed ready to pull the key back, "
        "and his mouth is set in a wary tight line. the skeleton key, matching the "
        "third reference image — A small iron skeleton key with a wooden tag-like "
        "handle. A symbol is carved into the handle: sharp lines, a round moon, and a "
        "shape like a little door. — is the central object between them. Warm "
        "town-square light, tense and suspicious. Stormy matches the first reference; "
        "the rat matches the second reference; the skeleton key matches the third "
        "reference."
    ),
    "rat_temple_challenge": (
        f"{ART} A small open square in town with simple felted buildings around the "
        "edges and a packed-dirt floor. The road out of town is visible behind the "
        "characters. Reference images are provided in this order: first Stormy, second "
        "the rat, and third the skeleton key. Stormy, matching the first reference "
        "image — A grey rabbit archer wearing a green cloak, with a small quiver of "
        "felted arrows on his back, carrying a wooden bow. — stands in the left "
        "foreground clutching the skeleton key tight against his chest with both paws, "
        "his body turned slightly away from the rat. His ears are pinned back in "
        "defiance, his eyes are narrowed with fierce determination, and his mouth is "
        "pulled into a hard stubborn frown. the rat, matching the second reference "
        "image — A brown giant rat tonic-salesman wearing a patched black top hat, a "
        "tailored dark coat over a smart buttoned vest with a brass watch chain, and a "
        "small bow tie, with a long pink tail. — stands on the right pointing "
        "dramatically down the road with one extended paw and tapping the side of his "
        "nose with the other. His eyes are bright with sly challenge and his mouth is "
        "curled into a thin competitive grin. Warm town-square light. Stormy matches "
        "the first reference; the rat matches the second reference; the skeleton key "
        "matches the third reference."
    ),
    "the_long_wait": (
        f"{ART} A small open square in town with simple felted buildings around the "
        "edges and a packed-dirt floor. The tonic cart and road are visible in the "
        "background, the square now quiet and mostly empty. Use the reference image "
        "for Stormy. Stormy, matching the first reference image — A grey rabbit "
        "archer wearing a green cloak, with a small quiver of felted arrows on his "
        "back, carrying a wooden bow. — sits alone on a low crate in the center of "
        "the square at sunset, shoulders slumped forward, both empty paws resting "
        "limp in his lap where the key should be. His ears droop sadly to either "
        "side, his eyes look down with worried hollow exhaustion, and his mouth is "
        "pulled into a small miserable frown. Warm sunset light with long soft "
        "shadows. Stormy has no key in his paws — outfit and proportions otherwise "
        "match the first reference."
    ),
    "shrine_door": (
        f"{ART} A marble shrine with a domed roof, set on top of a hill. A stone "
        "path leads up to the door, and a full moon hangs in the sky behind it. "
        "Reference images are provided in this order: first Stormy, second the "
        "skeleton key. Stormy, matching the first reference image — A grey rabbit "
        "archer wearing a green cloak, with a small quiver of felted arrows on his "
        "back, carrying a wooden bow. — stands before the shrine door in the "
        "foreground on the stone path, holding the skeleton key up in one raised paw "
        "while his other paw shields his eyes as he looks upward. His ears are perked "
        "forward in startled alarm, his eyes are wide looking up at something "
        "whistling overhead out of frame, and his mouth is open in a small surprised "
        "gasp. the skeleton key, matching the second reference image — A small iron "
        "skeleton key with a wooden tag-like handle. A symbol is carved into the "
        "handle: sharp lines, a round moon, and a shape like a little door. — has a "
        "symbol on it that visibly matches the symbol carved on the shrine door "
        "behind him. Cool moonlit light with soft shadows. Stormy matches the first "
        "reference; the skeleton key matches the second reference."
    ),
    "rat_rocket_arrival": (
        f"{ART} A marble shrine with a domed roof, set on top of a hill. A stone path "
        "leads up to the door, and a full moon hangs in the sky behind it. Reference "
        "images are provided in this order: first Stormy, second the rat. the rat, "
        "matching the second reference image — A brown giant rat tonic-salesman wearing "
        "a patched black top hat, a tailored dark coat over a smart buttoned vest with "
        "a brass watch chain, and a small bow tie, with a long pink tail. — flies "
        "through the sky above the shrine strapped to a small felted firework rocket, "
        "his body rigid and leaning back. His top hat is flattened against his face, "
        "his long pink tail streams straight behind him, his eyes are wide round dots "
        "of panic, and his mouth is open in a shrieking yell. Stormy, matching the "
        "first reference image — A grey rabbit archer wearing a green cloak, with a "
        "small quiver of felted arrows on his back, carrying a wooden bow. — looks up "
        "from near the shrine door below in the lower frame, one paw raised to shield "
        "his face, his ears blown back by the rocket wind, his eyes wide with "
        "startled disbelief, and his mouth dropped open. The rocket and rat should be "
        "the clear focus, with Stormy small but readable below. Cool moonlit light "
        "with a bright warm rocket flare. The rat is strapped to a firework rocket "
        "with his hat flattened against his face — outfit and proportions otherwise "
        "match the second reference. Stormy matches the first reference."
    ),
    "rat_rocket_crash": (
        f"{ART} A marble shrine with a domed roof, set on top of a hill. A stone path "
        "leads up to the door, and a full moon hangs in the sky behind it. A small "
        "flower bed or patch of soft ground sits beside the stone steps. Reference "
        "images are provided in this order: first Stormy, second the rat, and third "
        "the skeleton key. the rat, matching the second reference image — A brown "
        "giant rat tonic-salesman wearing a patched black top hat, a tailored dark "
        "coat over a smart buttoned vest with a brass watch chain, and a small bow "
        "tie, with a long pink tail. — has crash-landed upside down beside an "
        "extinguished felted firework rocket, his legs tangled in the straps and his "
        "tail sticking up in the air. His eyes are dizzy spirals or X shapes, and his "
        "mouth is flopped open in a dazed groan. The rocket lies dark and unlit beside "
        "him with no flame, spark, or glow — only a little wispy smoke curling away. "
        "A dark charred scorch mark spreads across the soft ground beneath the crash, "
        "singed felt grass and blackened earth in a rough oval around the rocket and "
        "rat. Stormy, matching the first reference image — "
        "A grey rabbit archer wearing a green cloak, with a small quiver of felted "
        "arrows on his back, carrying a wooden bow. — walks calmly past him toward "
        "the shrine door in the foreground, one paw reaching for the door handle and "
        "the other holding the skeleton key at his side. His ears are forward with "
        "quiet determination, his eyes look ahead at the door, and his mouth is set "
        "in a small focused line. the skeleton key, matching the third reference "
        "image — A small iron skeleton key with a wooden tag-like handle. A symbol "
        "is carved into the handle: sharp lines, a round moon, and a shape like a "
        "little door. — is visible in Stormy's paw. Cool moonlit light with soft "
        "shadows and no warm rocket flare. The rat is upside-down and tangled beside "
        "the extinguished rocket on the scorch mark — outfit and proportions otherwise "
        "match the second reference. Stormy and the skeleton key match their references."
    ),
    "the_unlit_lantern": (
        f"{ART} The interior of a shrine with cut stone floors and a stone altar in "
        "the middle. Bright moonlight filters through the windows. Reference images "
        "are provided in this order: first Stormy, second the lantern. the lantern, "
        "matching the second reference image — A small handheld lantern with a square "
        "dark-iron frame and pale clear paneled sides, decorated with small felted "
        "star and crescent-moon shapes set into the panels. A little ring handle sits "
        "on top. The interior is empty when unlit. — rests unlit and plain on the "
        "stone altar in the center, with no visible flame inside. Stormy, matching "
        "the first reference image — A grey rabbit archer wearing a green cloak, with "
        "a small quiver of felted arrows on his back, carrying a wooden bow. — stands "
        "beside the altar in the foreground, holding the lantern up in both paws and "
        "turning it over to examine it. His ears are tilted forward with puzzlement, "
        "his eyes are narrowed studying the empty interior, and his mouth is pulled "
        "into a small worried frown. Cool moonlight spills through the windows with "
        "soft shadows. Stormy matches the first reference; the lantern matches the "
        "second reference."
    ),
    "the_light_within": (
        f"{ART} The interior of a shrine with cut stone floors and a stone altar in "
        "the middle. Bright moonlight filters through the windows. Reference images "
        "are provided in this order: first Stormy, second the lantern. Stormy, "
        "matching the first reference image — A grey rabbit archer wearing a green "
        "cloak, with a small quiver of felted arrows on his back, carrying a wooden "
        "bow. — kneels in the center of the frame holding the lantern carefully in "
        "both paws at chest height, his eyes closed and his face tilted slightly "
        "upward. His ears are relaxed and lowered peacefully, his mouth is held in a "
        "soft brave little smile, and his whole posture is calm and still. the "
        "lantern, matching the second reference image — A small handheld lantern with "
        "a square dark-iron frame and pale clear paneled sides, decorated with small "
        "felted star and crescent-moon shapes set into the panels. A little ring "
        "handle sits on top. The interior is empty when unlit. — has a tiny warm "
        "felted flame that has just kindled inside it, glowing gently against the cool "
        "moonlight. Cool moonlight mixed with a tiny warm lantern glow. The lantern "
        "now holds a tiny flame inside — frame and proportions otherwise match the "
        "second reference. Stormy matches the first reference."
    ),
    "the_frozen_pass": (
        f"{ART} A marble shrine with a domed roof, set on top of a hill. A stone path "
        "leads up to the door, and a full moon hangs in the sky behind it. The shrine "
        "doorway sits behind Stormy and a wide frozen landscape stretches ahead under "
        "the moon. Reference images are provided in this order: first Stormy, second "
        "the lantern. Stormy, matching the first reference image — A grey rabbit "
        "archer wearing a green cloak, with a small quiver of felted arrows on his "
        "back, carrying a wooden bow. — steps out of the shrine onto the stone path "
        "in the foreground, holding the lit lantern in both paws at chest height. His "
        "ears are perked forward with quiet resolve, his eyes look ahead at the frozen "
        "land with determined focus, and his mouth is set in a small brave line. The "
        "lantern casts a small warm glow on his face and cloak. the lantern, matching "
        "the second reference image — A small handheld lantern with a square dark-iron "
        "frame and pale clear paneled sides, decorated with small felted star and "
        "crescent-moon shapes set into the panels. A little ring handle sits on top. "
        "The interior is empty when unlit. — glows with a small warm felted flame. "
        "Ahead of him, the frozen land is wide, white, and cold-looking. Behind him "
        "near the shrine steps, the crashed rat and rocket can be barely visible as a "
        "secondary background detail. Cool moonlight with warm lantern glow on Stormy. "
        "The lantern now glows with a small warm flame — frame and proportions "
        "otherwise match the second reference. Stormy matches the first reference."
    ),
}


def main() -> None:
    data = json.loads(STORY.read_text(encoding="utf-8"))
    for scene_id, description in UPDATES.items():
        if scene_id not in data["scenes"]:
            raise KeyError(f"unknown scene: {scene_id}")
        data["scenes"][scene_id]["LLMImageDescription"] = description
    STORY.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Updated {len(UPDATES)} scenes.")


if __name__ == "__main__":
    main()
